# Generated by Django 4.1.5 on 2023-01-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_active_comments_active_news_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
